### ISSUE TITLE
ScanObjectNN

### ISSUE THREAD

**Issue by upc-luxl** [ShiQiu0419/GFNet#3]
Hello, could  you provide the code of experiment on dataset ScanObjectNN?

**Comment by ShiQiu0419** [comment]
Hi, thanks for your interests in our work.

Basically, the codes for loading the data are from https://github.com/upc-luxl/dgcnn/blob/master/pytorch/data.py since ScanObjectNN data structure is similar as HDF5 modelnet40. Also, you can use the same codes from DGCNN (pytorch) for evaluation or data augmentation if needed.

**Comment by ShiQiu0419** [comment]
Hi @upc-luxl ,

Both the codes and pre-trained models for point cloud classification including ModelNet40 and ScanObjectNN datasets are fully avaible now. Thanks for your attention!
