### ISSUE TITLE
When will you publish the code?

### ISSUE THREAD

**Issue by caiyu97** [ShiQiu0419/GFNet#4]
Congratulation on the acceptance of your paper. I'm very interested in your work.When will you publish the code?

**Comment by ShiQiu0419** [comment]
Hi @caiyu97,
Thanks for your interests. Since currently we are busy with other projects and this one was implemented a quite long time ago, we may need more time cleaning up the codes. In this case, we suggest you to begin with [DGCNN (pytorch) ](https://github.com/WangYueFt/dgcnn/tree/master/pytorch) , then you would be ready to go with ours once the codes are released.

**Comment by ShiQiu0419** [comment]
Hi @caiyu97 ,

Both the codes and pre-trained models for point cloud classification including ModelNet40 and ScanObjectNN datasets are fully avaible now. Thanks for your attention!
